-- MySQL Script generated by MySQL Workbench
-- mar 08 oct 2019 15:11:59 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema house-targaryen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema house-targaryen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `house-targaryen` DEFAULT CHARACTER SET utf8 ;
USE `house-targaryen` ;

-- -----------------------------------------------------
-- Table `house-targaryen`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house-targaryen`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoP` VARCHAR(45) NOT NULL,
  `apellidoM` VARCHAR(45) NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `house-targaryen`.`VideoJuego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house-targaryen`.`VideoJuego` (
  `idVideoJuego` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `clasificacion` VARCHAR(45) NULL,
  `consola` VARCHAR(45) NULL,
  `precio` DOUBLE NOT NULL,
  PRIMARY KEY (`idVideoJuego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `house-targaryen`.`Tener`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house-targaryen`.`Tener` (
  `Usuario_idUsuario` INT NOT NULL,
  `VideoJuego_idVideoJuego` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `VideoJuego_idVideoJuego`),
  INDEX `fk_Usuario_has_VideoJuego_VideoJuego1_idx` (`VideoJuego_idVideoJuego` ASC),
  INDEX `fk_Usuario_has_VideoJuego_Usuario_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_VideoJuego_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `house-targaryen`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_VideoJuego_VideoJuego1`
    FOREIGN KEY (`VideoJuego_idVideoJuego`)
    REFERENCES `house-targaryen`.`VideoJuego` (`idVideoJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
